### ISSUE TITLE
Doesn't work with most terminal emulators. 

### ISSUE THREAD

**Issue by iskios** [eldritch-theme/fastfetch#1]
I usually use Terminator for its ability to keep it's position across launches, but it cannot render your theme properly. All the text looks great, but the image does not render in the terminal. The same is true of Alacritty, Wezterm, and all the others I have tried. Kitty seems to be the only one that works. 

May I ask if you know of something I can do to make Terminator to work with these awesome theme for fastfetch?

**Comment by neonvoidx** [comment]
You will need to read fastfetch documentation, the config uses kitty protocol by default so you'll need to change it in the config.
It's one of the top lines

**Comment by iskios** [comment]
Apologies
